Write a Python program to get the largest number from a list

In [2]:
# Define a list of numbers
numbers = [15, 5, 3, 48, 22, 99, 97]

# Use the max() function to find the largest number
largest = max(numbers)

# Print the result
print("The largest number in the list is:", largest)

The largest number in the list is: 99

Write a Python program to get the smallest number from a list

In [3]:
# Define a list of numbers
numbers = [20, 5, 77, 44, 22, 40, 1]

# Get the smallest number using min()
smallest = min(numbers)

# Print the result
print("The smallest number in the list is:", smallest)

The smallest number in the list is: 1

Write a Python script to add a key to a dictionary.

In [4]:
# Initial dictionary
person = {
    "name": "Joshua",
    "age": 20
}

# Add a new key-value pair
person["city"] = "Kwara"

# Print updated dictionary
print("Updated dictionary:", person)

Updated dictionary: {'name': 'Joshua', 'age': 20, 'city': 'Kwara'}

Write a Python script to merge two Python dictionaries

In [5]:
# Define two dictionaries
dict1 = {"name": "Joshua", "age": 20}
dict2 = {"city": "Kwara", "country": "Nigeria"}

# Merge dict2 into dict1
dict1.update(dict2)

# Print the merged dictionary
print("Merged dictionary:", dict1)

Merged dictionary: {'name': 'Joshua', 'age': 20, 'city': 'Kwara', 'country': 'Nigeria'}

Write a Python program to remove a key from a dictionary

In [6]:
# Define a dictionary
person = {
    "name": "Joshua",
    "age": 20,
    "city": "Kwara"
}

# Remove the 'city' key
removed_value = person.pop("city")

# Print the updated dictionary and removed value
print("Updated dictionary:", person)
print("Removed value:", removed_value)

Updated dictionary: {'name': 'Joshua', 'age': 20}
Removed value: Kwara

Write a Python program to convert a list to a tuple.

In [7]:
# Define a list
my_list = [2, 3, 4, 5, 6]

# Convert the list to a tuple
my_tuple = tuple(my_list)

# Print the result
print("Original list:", my_list)
print("Converted tuple:", my_tuple)

Original list: [2, 3, 4, 5, 6]
Converted tuple: (2, 3, 4, 5, 6)